#!/usr/bin/env python3
"""Generate ~4 weeks of realistic, contract-shaped call data.

Generic "Customer Service Inquiry" filler reads as a template and kills the
demo. Everything here is shaped to survive an SLT Mobitel ops manager looking
at it and thinking "yes, that's what our Tuesdays look like":

  * diurnal + weekly volume curve (evening peak, Monday spike, Sunday trough)
  * intent mix weighted to a Sri Lankan telco's real call reasons
  * language mix weighted BY DISTRICT (Tamil-dominant in the north and east)
  * containment that varies honestly by intent — high on reloads, low on faults
  * sentiment that genuinely improves on resolved calls and degrades otherwise
  * repeat callers generated by unresolved calls actually calling back
  * a planted broadband-fault surge in Gampaha inside the last 2 hours, so the
    emerging-issue detector has something real to fire on

Everything is anchored to `now` at run time. Re-run this on the morning of the
demo so timestamps read as today — see README "Demo-day runbook".

    python scripts/generate_seed.py [--days 28] [--per-day 360] [--reset]
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import random
import sys
import uuid
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app import db, ingest  # noqa: E402
from app.models import Action, CallRecord  # noqa: E402
from app.phone import affected_number  # noqa: E402

TZ = ZoneInfo("Asia/Colombo")

# ---------------------------------------------------------------------------
# Distributions
# ---------------------------------------------------------------------------

# intent -> (share, containment rate, median duration sec, base sentiment start)
INTENTS: dict[str, tuple[float, float, int, float]] = {
    "bill_inquiry":       (15.0, 0.88, 150, -0.15),
    "reload_topup":       (14.0, 0.94,  95,  0.05),
    "data_package":       (12.0, 0.86, 140,  0.00),
    "data_balance":       (10.0, 0.96,  70,  0.10),
    "broadband_fault":    ( 9.0, 0.52, 300, -0.55),
    "bill_payment":       ( 7.0, 0.83, 160, -0.10),
    "mobile_coverage":    ( 6.0, 0.55, 240, -0.45),
    "broadband_speed":    ( 5.0, 0.48, 280, -0.50),
    "router_wifi":        ( 4.0, 0.58, 260, -0.30),
    "peo_tv":             ( 4.0, 0.62, 210, -0.25),
    "sim_services":       ( 4.0, 0.66, 200, -0.10),
    "package_change":     ( 3.5, 0.74, 190,  0.05),
    "roaming":            ( 2.5, 0.71, 180,  0.00),
    "complaint_followup": ( 2.5, 0.44, 230, -0.65),
    "new_connection":     ( 2.0, 0.58, 260,  0.15),
    "general_info":       ( 2.0, 0.92,  90,  0.10),
    "disconnection":      ( 1.5, 0.30, 290, -0.40),
    "other":              ( 1.0, 0.35, 170, -0.05),
}

# district -> (share, (P(si), P(ta), P(en)))
DISTRICTS: dict[str, tuple[float, tuple[float, float, float]]] = {
    "Colombo":      (18.0, (0.62, 0.16, 0.22)),
    "Gampaha":      (14.0, (0.86, 0.05, 0.09)),
    "Kandy":        ( 8.0, (0.78, 0.13, 0.09)),
    "Kurunegala":   ( 7.0, (0.93, 0.02, 0.05)),
    "Kalutara":     ( 6.0, (0.90, 0.04, 0.06)),
    "Galle":        ( 5.5, (0.91, 0.03, 0.06)),
    "Ratnapura":    ( 5.0, (0.92, 0.04, 0.04)),
    "Jaffna":       ( 4.5, (0.06, 0.89, 0.05)),
    "Anuradhapura": ( 4.0, (0.94, 0.03, 0.03)),
    "Batticaloa":   ( 3.5, (0.08, 0.87, 0.05)),
    "Matara":       ( 3.5, (0.92, 0.02, 0.06)),
    "Badulla":      ( 3.0, (0.80, 0.16, 0.04)),
    "Puttalam":     ( 3.0, (0.83, 0.11, 0.06)),
    "Trincomalee":  ( 2.5, (0.35, 0.60, 0.05)),
    "Ampara":       ( 2.5, (0.42, 0.54, 0.04)),
    "Nuwara Eliya": ( 2.5, (0.50, 0.46, 0.04)),
    "Kegalle":      ( 2.5, (0.93, 0.03, 0.04)),
    "Matale":       ( 2.0, (0.85, 0.11, 0.04)),
    "Hambantota":   ( 2.0, (0.96, 0.01, 0.03)),
    "Polonnaruwa":  ( 1.8, (0.94, 0.03, 0.03)),
    "Monaragala":   ( 1.5, (0.95, 0.02, 0.03)),
    "Vavuniya":     ( 1.2, (0.20, 0.76, 0.04)),
    "Mannar":       ( 0.8, (0.10, 0.86, 0.04)),
    "Kilinochchi":  ( 0.7, (0.04, 0.93, 0.03)),
    "Mullaitivu":   ( 0.6, (0.05, 0.92, 0.03)),
}

# Local clock. Evening peak is real for a consumer telco.
HOUR_WEIGHTS = [
    0.4, 0.25, 0.2, 0.2, 0.3, 0.7, 1.6, 3.2, 5.5, 7.2, 8.0, 7.6,
    6.4, 5.8, 6.0, 6.4, 7.0, 7.8, 8.4, 7.6, 5.8, 3.8, 2.0, 1.0,
]
# Monday = 0
DOW_WEIGHTS = [1.22, 1.08, 1.05, 1.03, 1.10, 0.85, 0.62]

ESCALATION_BY_INTENT: dict[str, list[tuple[str, float]]] = {
    "broadband_fault":    [("intent_not_supported", 4), ("policy_required_human", 3), ("caller_requested_human", 2), ("high_frustration", 2), ("system_error", 1)],
    "broadband_speed":    [("intent_not_supported", 4), ("caller_requested_human", 3), ("high_frustration", 2), ("repeated_misunderstanding", 1)],
    "disconnection":      [("policy_required_human", 7), ("caller_requested_human", 2), ("high_frustration", 1)],
    "complaint_followup": [("caller_requested_human", 4), ("high_frustration", 3), ("intent_not_supported", 2), ("policy_required_human", 1)],
    "mobile_coverage":    [("intent_not_supported", 4), ("caller_requested_human", 2), ("system_error", 2), ("high_frustration", 1)],
    "bill_payment":       [("authentication_failed", 4), ("system_error", 3), ("caller_requested_human", 2)],
    "sim_services":       [("authentication_failed", 5), ("policy_required_human", 3), ("caller_requested_human", 2)],
    "new_connection":     [("policy_required_human", 4), ("intent_not_supported", 3), ("caller_requested_human", 2)],
}
ESCALATION_DEFAULT = [
    ("caller_requested_human", 4), ("intent_not_supported", 3),
    ("repeated_misunderstanding", 2), ("authentication_failed", 2),
    ("high_frustration", 2), ("system_error", 1), ("policy_required_human", 1),
]

TOPICS_BY_INTENT: dict[str, list[str]] = {
    "bill_inquiry":       ["billing", "charges", "statement", "overcharge"],
    "bill_payment":       ["billing", "payment", "card_declined"],
    "reload_topup":       ["reload", "prepaid", "voucher"],
    "data_package":       ["data", "package", "activation"],
    "data_balance":       ["data", "balance"],
    "broadband_fault":    ["outage", "no_connection", "fibre", "adsl"],
    "broadband_speed":    ["slow_speed", "throttling", "fibre"],
    "router_wifi":        ["router", "wifi", "equipment"],
    "mobile_coverage":    ["signal", "dropped_calls", "tower"],
    "peo_tv":             ["peo_tv", "channels", "set_top_box"],
    "sim_services":       ["sim", "puk", "esim", "replacement"],
    "roaming":            ["roaming", "international"],
    "package_change":     ["package", "upgrade", "downgrade"],
    "new_connection":     ["new_connection", "installation"],
    "disconnection":      ["cancellation", "retention"],
    "complaint_followup": ["complaint", "ticket_followup"],
    "general_info":       ["general", "outlet"],
    "other":              ["misc"],
}

ACTIONS_BY_INTENT: dict[str, list[str]] = {
    "bill_inquiry":     ["lookup_account", "fetch_bill", "explain_charges"],
    "bill_payment":     ["lookup_account", "take_payment", "send_receipt_sms"],
    "reload_topup":     ["lookup_account", "apply_reload", "send_confirmation_sms"],
    "data_package":     ["lookup_account", "list_packages", "activate_package"],
    "data_balance":     ["lookup_account", "fetch_balance"],
    "broadband_fault":  ["lookup_account", "run_line_test", "raise_fault_ticket"],
    "broadband_speed":  ["lookup_account", "run_speed_diagnostic", "raise_fault_ticket"],
    "router_wifi":      ["lookup_account", "remote_router_reboot", "send_setup_guide"],
    "mobile_coverage":  ["lookup_account", "check_cell_status", "raise_coverage_ticket"],
    "peo_tv":           ["lookup_account", "refresh_set_top_box", "raise_fault_ticket"],
    "sim_services":     ["verify_identity", "order_sim_replacement"],
    "roaming":          ["lookup_account", "activate_roaming", "send_tariff_sms"],
    "package_change":   ["lookup_account", "list_packages", "schedule_package_change"],
    "new_connection":   ["check_coverage", "capture_lead"],
    "disconnection":    ["lookup_account", "offer_retention", "log_disconnection_request"],
    "complaint_followup": ["lookup_ticket", "fetch_ticket_status"],
    "general_info":     ["fetch_outlet_info"],
    "other":            ["lookup_account"],
}

CHURN_SIGNALS = [
    "mentioned_competitor", "asked_about_disconnection", "threatened_to_leave",
    "repeat_unresolved_issue", "price_complaint", "asked_for_contract_end_date",
]

UPSELL_BY_INTENT: dict[str, list[str]] = {
    "broadband_speed": ["fibre_upgrade"],
    "broadband_fault": ["fibre_upgrade"],
    "data_package":    ["data_addon", "postpaid_migration"],
    "data_balance":    ["data_addon"],
    "reload_topup":    ["postpaid_migration"],
    "peo_tv":          ["peo_tv_bundle"],
    "package_change":  ["fibre_upgrade", "peo_tv_bundle"],
    "roaming":         ["roaming_pack"],
    "bill_inquiry":    ["postpaid_migration"],
}

# Weighted so a handful dominate — that is what makes the ranked
# knowledge-gap panel actionable rather than a flat list of one-offs.
UNANSWERED_POOL: list[tuple[str, float]] = [
    ("Can I temporarily pause my broadband while I am abroad?", 9),
    ("Why was I charged a reconnection fee after paying on time?", 8),
    ("How do I transfer my connection to a new address?", 8),
    ("Can I split my bill across two payment methods?", 6),
    ("What is the exact fibre availability at my address?", 6),
    ("How do I add a family member to my postpaid account?", 5),
    ("Can I keep my number if I move to a different package?", 5),
    ("Why is my PEO TV package missing channels I paid for?", 4),
    ("What compensation applies for an outage lasting over 24 hours?", 4),
    ("How do I claim the corporate discount for my company?", 3),
    ("Can I get an itemised call record for last month?", 3),
    ("Is there a student data plan available?", 2),
]

SUMMARY_TEMPLATES: dict[str, list[str]] = {
    "broadband_fault":  ["Customer in {d} reported broadband down since {t}. Line test run, fault ticket raised.",
                         "No connection reported in {d}. Diagnostics showed a line fault; ticket created."],
    "broadband_speed":  ["Customer in {d} reported speeds well below package. Speed diagnostic run.",
                         "Slow browsing reported in {d}, especially in the evenings."],
    "bill_inquiry":     ["Customer queried an unexpected charge on this month's bill. Charges explained.",
                         "Bill breakdown requested and provided for the current cycle."],
    "bill_payment":     ["Customer paid the outstanding balance; receipt sent by SMS.",
                         "Payment attempt failed on card; alternative payment method arranged."],
    "reload_topup":     ["Prepaid reload applied and confirmed by SMS.",
                         "Reload had not reflected; re-applied and confirmed."],
    "data_package":     ["Customer activated a monthly data package after comparing options.",
                         "Data package changed at the customer's request."],
    "data_balance":     ["Remaining data balance and validity confirmed to the customer."],
    "mobile_coverage":  ["Customer in {d} reported dropped calls. Cell status checked, ticket raised.",
                         "Weak signal reported in {d}; coverage ticket created."],
    "router_wifi":      ["Router rebooted remotely; customer confirmed WiFi restored.",
                         "WiFi setup guidance provided and setup guide sent."],
    "peo_tv":           ["PEO TV set-top box refreshed; channels restored.",
                         "Customer reported missing channels on their PEO TV package."],
    "sim_services":     ["Identity verified and SIM replacement ordered.",
                         "PUK provided after identity verification."],
    "roaming":          ["Roaming activated ahead of travel; tariffs sent by SMS."],
    "package_change":   ["Package upgrade scheduled for the next billing cycle."],
    "new_connection":   ["Coverage checked for a new fibre connection in {d}; lead captured."],
    "disconnection":    ["Customer requested disconnection. Retention offer presented.",
                         "Disconnection request logged after retention offer declined."],
    "complaint_followup": ["Customer chasing an existing ticket with no update. Status fetched.",
                           "Follow-up on an unresolved complaint from earlier this week."],
    "general_info":     ["Nearest outlet location and opening hours provided."],
    "other":            ["General enquiry handled."],
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _weighted(items: dict | list, rng: random.Random):
    if isinstance(items, dict):
        keys = list(items)
        weights = [v[0] if isinstance(v, tuple) else v for v in items.values()]
    else:
        keys = [k for k, _ in items]
        weights = [w for _, w in items]
    return rng.choices(keys, weights=weights, k=1)[0]


def _caller_hash(caller_id: int) -> str:
    return "sha256:" + hashlib.sha256(f"94{700000000 + caller_id}".encode()).hexdigest()[:32]


def _clamp(v: float, lo: float = -1.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, v))


def _pick_language(district: str, rng: random.Random) -> tuple[str, list[str]]:
    p_si, p_ta, p_en = DISTRICTS[district][1]
    primary = rng.choices(["si", "ta", "en"], weights=[p_si, p_ta, p_en], k=1)[0]
    mix = [primary]
    # Code-switching is the norm in Sri Lanka — English terms inside a Sinhala
    # or Tamil call. Showing this explicitly is a differentiator.
    if primary != "en" and rng.random() < 0.34:
        mix.append("en")
    return primary, mix


def _make_call(
    started: datetime,
    rng: random.Random,
    caller_pool: int,
    *,
    force_intent: str | None = None,
    force_district: str | None = None,
    force_contained: bool | None = None,
    caller_id: int | None = None,
    followup_of: str | None = None,
) -> CallRecord:
    intent = force_intent or _weighted(INTENTS, rng)
    district = force_district or _weighted(DISTRICTS, rng)
    share, containment, median_dur, base_sent = INTENTS[intent]

    lang, lang_mix = _pick_language(district, rng)

    # Outcome ----------------------------------------------------------------
    if force_contained is None:
        r = rng.random()
        if r < 0.028:
            handled_by = "abandoned"
        elif r < containment * 0.97 + 0.028:
            handled_by = "ai"
        else:
            handled_by = "escalated" if rng.random() < 0.88 else "transferred_ivr"
    else:
        handled_by = "ai" if force_contained else "escalated"

    resolved = handled_by == "ai" and rng.random() < 0.94
    if handled_by == "escalated":
        resolved = False  # resolved by a human downstream; not by us

    escalation_reason = None
    if handled_by == "escalated":
        escalation_reason = _weighted(
            ESCALATION_BY_INTENT.get(intent, ESCALATION_DEFAULT), rng
        )

    # Duration ---------------------------------------------------------------
    duration = max(20, int(rng.gauss(median_dur, median_dur * 0.34)))
    if handled_by == "abandoned":
        duration = rng.randint(8, 45)
    elif handled_by == "escalated":
        duration = int(duration * rng.uniform(1.15, 1.6))
    ai_sec = duration if handled_by == "ai" else int(duration * rng.uniform(0.35, 0.7))
    queue_wait = rng.choices([0, 1, 2, 3, 5, 8], weights=[40, 25, 15, 10, 7, 3], k=1)[0]

    # Sentiment --------------------------------------------------------------
    s_start = _clamp(rng.gauss(base_sent, 0.22))
    if handled_by == "ai" and resolved:
        s_end = _clamp(s_start + rng.uniform(0.35, 0.95))
    elif handled_by == "escalated":
        s_end = _clamp(s_start + rng.uniform(-0.12, 0.22))
    elif handled_by == "abandoned":
        s_end = _clamp(s_start - rng.uniform(0.05, 0.35))
    else:
        s_end = _clamp(s_start + rng.uniform(0.0, 0.3))

    csat = int(round(_clamp((s_end + 1) / 2 * 4 + 1 + rng.gauss(0, 0.35), 1, 5)))

    # Churn ------------------------------------------------------------------
    churn_base = {"disconnection": 0.82, "complaint_followup": 0.42,
                  "broadband_fault": 0.16, "broadband_speed": 0.18,
                  "bill_inquiry": 0.07}.get(intent, 0.03)
    if not resolved:
        churn_base += 0.12
    if s_end < -0.3:
        churn_base += 0.15
    churn_risk = rng.random() < churn_base
    churn_signals = (
        rng.sample(CHURN_SIGNALS, k=rng.randint(1, 3)) if churn_risk else []
    )

    # Upsell -----------------------------------------------------------------
    upsell = None
    candidates = UPSELL_BY_INTENT.get(intent)
    if candidates and handled_by == "ai" and s_end > 0.1 and rng.random() < 0.19:
        upsell = rng.choice(candidates)

    # Knowledge gaps ---------------------------------------------------------
    unanswered: list[str] = []
    gap_chance = 0.14 if handled_by == "escalated" else 0.045
    if rng.random() < gap_chance:
        unanswered.append(_weighted(UNANSWERED_POOL, rng))

    # Actions ----------------------------------------------------------------
    action_names = ACTIONS_BY_INTENT.get(intent, ["lookup_account"])
    n_actions = len(action_names) if handled_by == "ai" else max(1, len(action_names) - 1)
    actions = []
    for i, name in enumerate(action_names[:n_actions]):
        ok = not (handled_by == "escalated" and i == n_actions - 1 and rng.random() < 0.3)
        ref = None
        if ok and name.startswith("raise_") :
            ref = f"FLT-{rng.randint(100000, 999999)}"
        actions.append(Action(action=name, status="ok" if ok else "failed", ref=ref))

    topics = list(TOPICS_BY_INTENT.get(intent, ["misc"]))
    rng.shuffle(topics)
    topics = topics[: rng.randint(1, min(3, len(topics)))]

    summary = rng.choice(SUMMARY_TEMPLATES.get(intent, ["Call handled."])).format(
        d=district, t=started.astimezone(TZ).strftime("%H:%M")
    )
    if followup_of:
        summary = "Repeat call — " + summary

    cid = caller_id if caller_id is not None else rng.randint(0, caller_pool - 1)

    return CallRecord(
        call_id=f"call_{uuid.uuid4().hex[:20]}",
        started_at=started,
        ended_at=started + timedelta(seconds=duration),
        duration_sec=duration,
        ai_handling_sec=ai_sec,
        queue_wait_sec=queue_wait,
        caller_hash=_caller_hash(cid),
        district=district,
        customer_segment=rng.choices(
            ["prepaid", "postpaid", "fixed", "enterprise"],
            weights=[52, 26, 18, 4], k=1
        )[0],
        channel="voice_inbound",
        affected_number=affected_number(intent, district, rng),
        intent=intent,
        sub_intent=None,
        topics=topics,
        language_primary=lang,
        language_mix=lang_mix,
        handled_by=handled_by,
        resolved=resolved,
        escalation_reason=escalation_reason,
        actions_taken=actions,
        sentiment_start=round(s_start, 3),
        sentiment_end=round(s_end, 3),
        csat_predicted=csat,
        interruptions=rng.choices([0, 1, 2, 3], weights=[62, 24, 10, 4], k=1)[0],
        silence_ratio=round(abs(rng.gauss(0.09, 0.05)), 3),
        churn_risk=churn_risk,
        churn_signals=churn_signals,
        upsell_opportunity=upsell,
        unanswered_questions=unanswered,
        summary=summary,
        enrichment_model="claude-opus-4-8",
        enrichment_confidence=round(rng.uniform(0.78, 0.99), 3),
    )


def _day_volume(day: datetime, per_day: int, rng: random.Random) -> int:
    weight = DOW_WEIGHTS[day.weekday()]
    return max(1, int(rng.gauss(per_day * weight, per_day * 0.07)))


def build(days: int, per_day: int, seed: int) -> list[CallRecord]:
    rng = random.Random(seed)
    now = datetime.now(TZ).replace(microsecond=0)
    caller_pool = max(500, per_day * days // 3)

    calls: list[CallRecord] = []

    # --- baseline traffic --------------------------------------------------
    for day_offset in range(days, 0, -1):
        day_start = (now - timedelta(days=day_offset)).replace(
            hour=0, minute=0, second=0, microsecond=0
        )
        for _ in range(_day_volume(day_start, per_day, rng)):
            hour = rng.choices(range(24), weights=HOUR_WEIGHTS, k=1)[0]
            started = day_start + timedelta(
                hours=hour, minutes=rng.randint(0, 59), seconds=rng.randint(0, 59)
            )
            if started >= now:
                continue
            calls.append(_make_call(started, rng, caller_pool))

    # Today so far, up to the current hour.
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    elapsed_weight = sum(HOUR_WEIGHTS[: now.hour + 1])
    today_target = int(per_day * DOW_WEIGHTS[now.weekday()] * elapsed_weight / sum(HOUR_WEIGHTS))
    for _ in range(today_target):
        hour = rng.choices(range(now.hour + 1), weights=HOUR_WEIGHTS[: now.hour + 1], k=1)[0]
        started = today_start + timedelta(
            hours=hour, minutes=rng.randint(0, 59), seconds=rng.randint(0, 59)
        )
        if started >= now:
            continue
        calls.append(_make_call(started, rng, caller_pool))

    # --- repeat callers ----------------------------------------------------
    # An unresolved call is the single best predictor of a call-back. Generating
    # these explicitly is what makes the first-contact-resolution proxy real
    # rather than an artefact of random caller collisions.
    followups: list[CallRecord] = []
    for c in calls:
        if c.resolved or c.handled_by == "abandoned":
            continue
        if rng.random() > 0.19:
            continue
        gap = timedelta(hours=rng.uniform(2.5, 22))
        started = c.started_at + gap
        if started >= now:
            continue
        caller_id = int(c.caller_hash[-6:], 16) % caller_pool  # irrelevant; overridden below
        f = _make_call(
            started, rng, caller_pool,
            force_intent="complaint_followup" if rng.random() < 0.45 else c.intent,
            force_district=c.district,
            followup_of=c.call_id,
        )
        f.caller_hash = c.caller_hash  # the whole point
        followups.append(f)
    calls.extend(followups)

    # --- planted incident: broadband outage in Gampaha ---------------------
    # Sits inside the detector's 2-hour window so the emerging-issue panel has
    # a real, defensible spike the moment the dashboard is opened.
    surge_calls = rng.randint(34, 46)
    for _ in range(surge_calls):
        started = now - timedelta(minutes=rng.uniform(3, 108))
        c = _make_call(
            started, rng, caller_pool,
            force_intent="broadband_fault",
            force_district="Gampaha",
            force_contained=rng.random() < 0.38,
        )
        c.topics = ["outage", "no_connection", "fibre"]
        c.sentiment_start = round(_clamp(rng.gauss(-0.72, 0.15)), 3)
        c.sentiment_end = round(_clamp(c.sentiment_start + rng.uniform(0.1, 0.6)), 3)
        c.summary = (
            "Customer in Gampaha reported broadband down. Multiple reports from "
            "the same area — suspected local outage. Fault ticket raised."
        )
        calls.append(c)

    # A second, smaller anomaly so the panel shows severity gradation rather
    # than a single all-caps alarm.
    for _ in range(rng.randint(9, 14)):
        started = now - timedelta(minutes=rng.uniform(5, 115))
        c = _make_call(
            started, rng, caller_pool,
            force_intent="peo_tv",
            force_district="Colombo",
            force_contained=rng.random() < 0.55,
        )
        c.topics = ["peo_tv", "channels"]
        calls.append(c)

    calls.sort(key=lambda c: c.started_at)
    return calls


# ---------------------------------------------------------------------------

async def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--days", type=int, default=28)
    ap.add_argument("--per-day", type=int, default=360)
    ap.add_argument("--seed", type=int, default=20260723)
    ap.add_argument("--reset", action="store_true", help="truncate calls and alerts first")
    ap.add_argument("--if-empty", action="store_true",
                    help="seed only when the calls table is empty (used by the Docker entrypoint)")
    args = ap.parse_args()

    await db.connect()
    await db.apply_schema()

    if args.if_empty:
        existing = await db.pool().fetchval("SELECT count(*) FROM calls")
        if existing:
            print(f"calls table already has {existing} rows — skipping seed")
            await db.disconnect()
            return

    if args.reset:
        async with db.pool().acquire() as conn:
            await conn.execute("TRUNCATE calls; TRUNCATE alerts;")
        print("cleared existing calls and alerts")

    print(f"generating ~{args.days} days at ~{args.per_day}/day ...")
    calls = build(args.days, args.per_day, args.seed)

    # Same code path as production ingest, so seeding also exercises it.
    CHUNK = 500
    for i in range(0, len(calls), CHUNK):
        await ingest.store(calls[i:i + CHUNK], broadcast=False)
        print(f"  {min(i + CHUNK, len(calls))}/{len(calls)}", end="\r", flush=True)

    async with db.pool().acquire() as conn:
        total = await conn.fetchval("SELECT count(*) FROM calls")
        newest = await conn.fetchval("SELECT max(started_at) FROM calls")
        contained = await conn.fetchval(
            "SELECT count(*) FILTER (WHERE handled_by='ai')::float / count(*) * 100 FROM calls"
        )

    print(f"\nseeded {len(calls)} calls  (table now {total})")
    print(f"newest call: {newest}")
    print(f"overall containment: {contained:.1f}%")

    await db.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
